Master
cruzocards/cruzo-contracts pull request #5
Opened 2022-05-31 17:56 UTC by suNrisEinMyeYes

fixed multiple trades through simple mapping

2022-05-31 20:07 UTC, bobrom commented
Could you please rebase your changes on top of the `develop` branch?

2022-05-31 20:09 UTC, bobrom requested changes

2022-05-31 20:09 UTC, bobrom commented on contracts/marketplace/CruzoMarket.sol
> +        require(addrToItem[msg.sender][_itemId] == false, "already in trades");
The check should include _tokenAddress, otherwise the mapping will have collisions when it's used with different tokens.

2022-05-31 20:09 UTC, bobrom commented on contracts/marketplace/CruzoMarket.sol
> +    mapping(address => uint256[]) addrToHisTrades;
Variable is not used. Could you please remove all the unused code?

2022-05-31 20:09 UTC, bobrom commented on contracts/marketplace/CruzoMarket.sol
> +
Excessive empty lines (here and after) should be removed.

2022-05-31 20:09 UTC, bobrom commented on contracts/marketplace/CruzoMarket.sol
> +        addrToItem[msg.sender][_itemId] = true;
Would it make sense to store the trades itself inside a nested mappings structure? Then we can get rid of the additional `addrToItem` mapping.

2022-06-01 03:48 UTC, suNrisEinMyeYes commented on contracts/marketplace/CruzoMarket.sol
> +
fixed

2022-06-01 03:49 UTC, suNrisEinMyeYes commented on contracts/marketplace/CruzoMarket.sol
> +        require(addrToItem[msg.sender][_itemId] == false, "already in trades");
agree, fixed

2022-06-01 03:55 UTC, suNrisEinMyeYes commented on contracts/marketplace/CruzoMarket.sol
> +        addrToItem[msg.sender][_itemId] = true;
it makes sense while using execute and cancel functions, but through opentrade, we dont have tradeId to check

2022-06-02 20:03 UTC, closed without merging